openapi: 3.0.2
info:
  title: 'OpenAPI Course'
  description: Specification for OpenAPI Course
  version: 1.0.0
  termsOfService: 'http://example.com/terms/'
  contact:
    name: Marcel Seuga
    email: sevgama44@gmail.com
  license:
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://dev.example.com'
    description: Development Server
  - url: 'https://qa.example.com'
    description: Question and Answer
  - url: 'https://prod.example.com'
    description: Production Server
paths:
  /v1/customers:
    get:
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                description: List of Customers
                items:
                  type: object
                  description: customer object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Marcel
                    lastName:
                      type: string
                      minLength: 2
                      maxLength: 100
                      example: Seuga
                    address:
                      type: object
                      properties:
                        line1:
                          type: string
                          example: 248 pineapple
                        city:
                          type: string
                          example: Greer
                        stateCode:
                          type: string
                          minLength: 2
                          maxLength: 2
                          description: 2 Letter State Code
                          # enum: [AL, AK, AZ, AR, CA]
                          enum:
                            -AL
                            -AK
                            -AZ
                            -AR
                            -CA
                        zipCode:
                          type: string
                          example: 30005
  /v1/beers:
    get:
      responses:
        '200':
          description: List of Beers
          content:
            application/json:
              schema:
                type: array
                description: List of beer object
                items:
                  type: object
                  description: Beer object
                  properties:
                    name:
                      type: string
                    style:
                      type: string
                      enum: [ALE, PALE_ALE, IPA, WHEAT, LAGER]
                    upc:
                      type: string
                    price:
                      type: number
                      format: float
                    quantity:
                      type: integer
                      format: int32
                    brewery:
                      type: object
                      properties:
                        name:
                          type: string
                        location:
                          type: string
        '404':
          description: No Beers Found


  